version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet_system
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB

  redis:
    image: redis:7-alpine
    container_name: wallet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru

  wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://wallet_user:wallet_password@postgres:5432/wallet_system
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_KEY: ${API_KEY:-6pfrn00011248xivxkz0t}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]

volumes:
  postgres_data:
  redis_data:
